# Manually run, generates a unity license file that should be saved into GitHub > Settings > Secrets

name: 🔑 Generate Unity License File (ALF)

on: workflow_dispatch

jobs:
  GetUnityLicenseFile:
    name: Generate Unity License File
    runs-on: ubuntu-latest
    container:
      image: "unityci/editor:ubuntu-2021.3.45f1-base-3.1.0"
    steps:
    - uses: actions/checkout@v2
    - run: /opt/unity/Editor/Unity -nographics -batchmode -createManualActivationFile -logfile || true
    - uses: actions/upload-artifact@v2
      with:
        path: Unity_v2021.3.45f1.alf
